### ISSUE TITLE
ngAtomicNotify directive DI problem

### ISSUE THREAD

**Issue by terranisu** [maxigimenez/angular-atomic-notify#11]
When I try to compress the lib using uglifier with mangle: true I get the error "Unknown Provider", because during the compression "$scope" parameter name has been changing here https://github.com/maxigimenez/angular-atomic-notify/blob/master/src/angular-atomic-notify.js#L102

The possible solution is to use DI in this line https://github.com/maxigimenez/angular-atomic-notify/blob/master/src/angular-atomic-notify.js#L128
Like that `['$scope', controller]`

I also can reproduce the problem even without a compression just using ng-strict-di directive. Then it says "Error: [$injector:strictdi] function($scope) is not using explicit annotation and cannot be invoked in strict mode"

Should I create a PR or you can fix it by yourself?

**Comment by maxigimenez** [comment]
Fixed on #12
