### ISSUE TITLE
ngAtomicNotify is undefined

### ISSUE THREAD

**Issue by atul221282** [maxigimenez/angular-atomic-notify#3]
I tried this but i am getting ur directive undefined when it gets to "displayNotify" function in your service.

On further debugging i found that 
angular.element('ng-atomic-notify').isolateScope() return nothing.

FYI all my view and controller are under parent controller 

Update:- The issue is if we use this directive under parent controller it doesn't work coz of scope issue but in a lot of cases you would maintain ur whole application via one parent controller not via rootscope. 

I will wait for your thoughts

**Comment by maxigimenez** [comment]
Already fixed in version 1.0.2
Thank you.
