### ISSUE TITLE
Rounded corners

### ISSUE THREAD

**Issue by alicona** [maxigimenez/angular-atomic-notify#5]
I finish working on make rounded corners, and changed the close button.  It looks like this so far

I will make a pull request soon

![image](https://cloud.githubusercontent.com/assets/93709/8484558/63e51f4c-20c6-11e5-8ec9-bf0dea3f9bfc.PNG)

**Comment by maxigimenez** [comment]
Related -> https://github.com/maxigimenez/angular-atomic-notify/pull/6
