### ISSUE TITLE
The 'ngAtomicNotify' directive doesn't use the array injection syntax.

### ISSUE THREAD

**Issue by easyt** [maxigimenez/angular-atomic-notify#7]
I'm unable to uglify the source because the 'ngAtomicNotify' directive is not specified using the array syntax. It should look similar to the following:

.directive('ngAtomicNotify', ['$compile', '$timeout', function($compile, $timeout){ ...

Could you please put in a fix and push an update to bower?

**Comment by maxigimenez** [comment]
Fixed on version 1.0.3
Thank you.
